###################################################################################
## Welcome to teamargos.org, a Jekyll-built static website!
##
## This config file is meant for settings that affect the whole site, values
##  which are expected to set up once and rarely edit after that. 
##  Frequently-updated configuration is found in the `_data` folder.
##
## Because of this, this file is *NOT* reloaded automatically when you use
##  'bundle exec jekyll serve'. If you change this file, please restart the 
##  server process.
###################################################################################

###################################################################################
## Overall Site Configuration
###################################################################################

title: Argos 1756
email: 1756argos1756@limestone310.org
description: > # this means to ignore newlines until "baseurl:"
  Argos Team 1756
  A community-based FIRST Robotics team serving the Peoria, IL area
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://teamargos.org" # the base hostname & protocol for your site, e.g. http://example.com

# Company Information
company_name: Argos
address_line_1: Limestone Community High School
address_line_2: 4201 Airport Rd
address_line_3: Peoria, IL 61607
company_email: 1756argos1756@limestone310.org
google_map: https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1062.4184415472848!2d-89.68225451183366!3d40.63877099870243!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x43621444ce21ed89!2zNDDCsDM4JzE5LjYiTiA4OcKwNDAnNTQuMSJX!5e1!3m2!1sen!2sus!4v1665960715060!5m2!1sen!2sus

# Social Links
facebook_link: https://www.facebook.com/TeamArgos1756
twitter_link: https://twitter.com/frc1756
youtube_link: https://www.youtube.com/channel/UC9RlFXg3JArplma4yucLBXA
instagram_link:
github_link: https://github.com/FRC1756-Argos
tba_link: https://www.thebluealliance.com/team/1756

###################################################################################
## Page Image/Video Banner Configurations
###################################################################################
banner_height: 525px

###################################################################################
## Custom Content Collections
###################################################################################
collections:

  # Tells the website generator that our history page should be assembled from
  #  all the different individual history year .md files.
  history:


###################################################################################
## Jekyll build configuration
###################################################################################
markdown: kramdown
plugins:
  - jekyll-feed
